-- mytheme.nvim/lua/mytheme/groups.lua
local colors = require("mytheme.palette")
local util = require("mytheme.util")

local comment = util.blend(colors.bg, colors.white, 0.35)
local cursorline = util.blend(colors.bg, colors.magenta, 0.15)
local diff_add = util.blend(colors.bg, colors.green, 0.2)
local diff_delete = util.blend(colors.bg, colors.red, 0.2)
local diff_change = util.blend(colors.bg, colors.blue, 0.2)
local diff_text = util.blend(colors.bg, colors.orange, 0.2)

local M = {}

M.setup = function()
  return {
    Normal = { fg = colors.fg, bg = colors.bg },
    NormalFloat = { fg = colors.fg, bg = cursorline },
    FloatBorder = { fg = comment, bg = cursorline },
    FloatTitle = { fg = colors.fg, bold = true },
    Cursor = { fg = colors.bg, bg = colors.magenta },
    CursorLine = { bg = cursorline },
    CursorLineNr = { fg = colors.fg, bold = false },
    CursorColumn = { bg = cursorline },
    LineNr = { fg = comment },
    SignColumn = { bg = colors.bg },
    ColorColumn = { bg = cursorline },
    WinSeparator = { fg = comment },
    StatusLine = { fg = colors.fg, bg = cursorline },
    StatusLineNC = { fg = comment, bg = cursorline },
    TabLine = { fg = comment, bg = cursorline },
    TabLineFill = { bg = cursorline },
    TabLineSel = { fg = colors.fg, bg = colors.bg, bold = true },
    WinBar = { fg = colors.fg },
    WinBarNC = { fg = comment },
    Title = { fg = colors.blue, bold = true },
    NonText = { fg = comment },
    EndOfBuffer = { fg = colors.bg },
    Folded = { fg = comment, bg = cursorline },
    FoldColumn = { fg = comment },
    Directory = { fg = colors.blue, bold = true },

    Visual = { fg = colors.bg, bg = colors.yellow },
    Search = { fg = colors.bg, bg = colors.yellow },
    IncSearch = { fg = colors.bg, bg = colors.magenta },
    CurSearch = { fg = colors.bg, bg = colors.magenta },
    Substitute = { fg = colors.bg, bg = colors.orange },
    MatchParen = { fg = colors.bright_yellow, bold = true },
    QuickFixLine = { bg = cursorline, bold = true },

    Pmenu = { fg = colors.fg, bg = cursorline },
    PmenuSel = { fg = colors.bg, bg = colors.yellow },
    PmenuSbar = { bg = cursorline },
    PmenuThumb = { bg = comment },
    PmenuKind = { fg = colors.blue, bg = cursorline },
    PmenuKindSel = { fg = colors.bg, bg = colors.yellow },

    DiffAdd = { bg = diff_add },
    DiffChange = { bg = diff_change },
    DiffDelete = { bg = diff_delete, fg = colors.red },
    DiffText = { bg = diff_text, bold = true },

    SpellBad = { sp = colors.red, undercurl = true },
    SpellCap = { sp = colors.blue, undercurl = true },
    SpellLocal = { sp = colors.cyan, undercurl = true },
    SpellRare = { sp = colors.magenta, undercurl = true },

    DiagnosticError = { fg = colors.red },
    DiagnosticWarn = { fg = colors.orange },
    DiagnosticInfo = { fg = colors.cyan },
    DiagnosticHint = { fg = colors.blue },

    Comment = { fg = comment, italic = true },
    Constant = { fg = colors.cyan },
    String = { fg = colors.cyan },
    Character = { fg = colors.cyan },
    Number = { fg = colors.orange },
    Boolean = { fg = colors.orange },
    Float = { fg = colors.orange },
    Identifier = { fg = colors.fg },
    Function = { fg = colors.blue },
    Statement = { fg = colors.magenta },
    Conditional = { fg = colors.magenta },
    Repeat = { fg = colors.magenta },
    Label = { fg = colors.magenta },
    Operator = { fg = colors.white },
    Keyword = { fg = colors.magenta },
    Exception = { fg = colors.red },
    PreProc = { fg = colors.orange },
    Include = { fg = colors.orange },
    Define = { fg = colors.orange },
    Macro = { fg = colors.orange },
    PreCondit = { fg = colors.orange },
    Type = { fg = colors.bright_salmon },
    StorageClass = { fg = colors.bright_salmon },
    Structure = { fg = colors.bright_salmon },
    Typedef = { fg = colors.bright_salmon },
    Special = { fg = colors.bright_yellow },
    SpecialChar = { fg = colors.bright_yellow },
    Tag = { fg = colors.magenta },
    Delimiter = { fg = colors.white },
    SpecialComment = { fg = comment, italic = true, bold = true },
    Debug = { fg = colors.red },
    Underlined = { fg = colors.blue, underline = true },
    Ignore = { fg = colors.bg },
    Error = { fg = colors.red, bold = true },
    Todo = { fg = colors.bg, bg = colors.bright_yellow, bold = true },

    ["@variable"] = { fg = colors.fg },
    ["@variable.builtin"] = { fg = colors.magenta, italic = true },
    ["@variable.parameter"] = { fg = colors.fg, italic = true },
    ["@variable.member"] = { fg = colors.white },
    ["@constant"] = { fg = colors.cyan },
    ["@constant.builtin"] = { fg = colors.orange, bold = true },
    ["@string"] = { fg = colors.cyan },
    ["@string.escape"] = { fg = colors.bright_salmon, bold = true },
    ["@character"] = { fg = colors.cyan },
    ["@number"] = { fg = colors.orange },
    ["@boolean"] = { fg = colors.orange },
    ["@function"] = { fg = colors.blue },
    ["@function.builtin"] = { fg = colors.blue, bold = true },
    ["@function.call"] = { fg = colors.blue },
    ["@method"] = { fg = colors.blue },
    ["@method.call"] = { fg = colors.blue },
    ["@constructor"] = { fg = colors.bright_salmon, bold = true },
    ["@keyword"] = { fg = colors.magenta },
    ["@keyword.function"] = { fg = colors.magenta, bold = true },
    ["@keyword.return"] = { fg = colors.magenta, bold = true },
    ["@keyword.operator"] = { fg = colors.magenta },
    ["@operator"] = { fg = colors.white },
    ["@type"] = { fg = colors.bright_salmon },
    ["@type.builtin"] = { fg = colors.bright_salmon, italic = true },
    ["@attribute"] = { fg = colors.orange },
    ["@property"] = { fg = colors.white },
    ["@punctuation.delimiter"] = { fg = colors.white },
    ["@punctuation.bracket"] = { fg = colors.white },
    ["@comment"] = { fg = comment, italic = true },
    ["@tag"] = { fg = colors.magenta },
    ["@tag.attribute"] = { fg = colors.orange },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.heading"] = { fg = colors.blue, bold = true },
    ["@markup.link"] = { fg = colors.cyan, underline = true },
  }
end

return M
